# Generated by Django 2.2.2 on 2019-06-26 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalExpenses',
            new_name='ExtraExpenses',
        ),
        migrations.RenameModel(
            old_name='AdditionalIncome',
            new_name='ExtraIncome',
        ),
    ]
